replicaCount: 1

image:
  repository: yourhostel/devops-final
  pullPolicy: Always
  tag: 

imagePullSecrets:
  - name: dockerhub-secret

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

namespace: python-app

