# ansible/playbooks/deploy.yml

---
- name: Setup Prometheus, Grafana, Node Exporter, and cAdvisor
  hosts: all
  become: yes
  vars:
    prometheus_host: "{{ groups['all'][0] }}"
    grafana_host: "{{ groups['all'][0] }}"
    cadvisor_hosts: "{{ groups['all'][0], groups['all'][2] }}"
    node_exporter_hosts: "{{ groups['all'] }}"
  roles:
    - role: prometheus
      when: inventory_hostname == prometheus_host
    - role: grafana
      when: inventory_hostname == grafana_host
    - role: c_advisor
      when: inventory_hostname in cadvisor_hosts
    - role: node_exporter
      when: inventory_hostname in node_exporter_hosts
