# ansible/roles/node_exporter/tasks/main.yml

---
- name: Create Node Exporter user and group
  user:
    name: node_exporter
    state: present
    shell: /sbin/nologin

- name: Download and install Node Exporter
  shell: |
    cd /opt
    if [ ! -d "node_exporter" ]; then
      wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
      tar -xvf node_exporter-1.3.1.linux-amd64.tar.gz
      mv node_exporter-1.3.1.linux-amd64 node_exporter
    fi
    chown -R node_exporter:node_exporter /opt/node_exporter
  args:
    executable: /bin/bash

- name: Create Node Exporter service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=node_exporter
      ExecStart=/opt/node_exporter/node_exporter

      [Install]
      WantedBy=default.target

- name: Enable and start Node Exporter service
  systemd:
    name: node_exporter
    enabled: yes
    state: started


