# homework-20240707/postgresql-variant-1/postgresql-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: default
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql
  type: ClusterIP