# ansible/playbooks/deploy.yml

---
- name: Setup Prometheus, Grafana, Node Exporter, and cAdvisor
  hosts: all
  become: yes
  roles:
    - node_exporter

- name: Setup Prometheus on observer
  hosts: prometheus_server
  become: yes
  roles:
    - prometheus
    - grafana
    - c_advisor

- name: Setup cAdvisor on target2
  hosts: target2
  become: yes
  roles:
    - c_advisor




