# ansible/playbooks/deploy.yml

---
- hosts: all
  become: yes
  tasks:
    - name: Update and install dependencies
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - amazon-linux-extras
        - wget
        - tar

- hosts: all
  become: yes
  tasks:
    - name: Install Prometheus
      when: inventory_hostname == groups['all'][0]
      block:
        - name: Create Prometheus user
          user:
            name: prometheus
            shell: /sbin/nologin

        - name: Download and install Prometheus
          shell: |
            cd /opt
            wget https://github.com/prometheus/prometheus/releases/download/v2.31.1/prometheus-2.31.1.linux-amd64.tar.gz
            tar -xvf prometheus-2.31.1.linux-amd64.tar.gz
            mv prometheus-2.31.1.linux-amd64 prometheus
            chown -R prometheus:prometheus /opt/prometheus

        - name: Create Prometheus service
          copy:
            dest: /etc/systemd/system/prometheus.service
            content: |
              [Unit]
              Description=Prometheus
              After=network.target

              [Service]
              User=prometheus
              ExecStart=/opt/prometheus/prometheus --config.file /opt/prometheus/prometheus.yml --storage.tsdb.path /opt/prometheus/data

              [Install]
              WantedBy=multi-user.target

        - name: Enable and start Prometheus service
          systemd:
            name: prometheus
            enabled: yes
            state: started

    - name: Install Node Exporter
      block:
        - name: Create Node Exporter user
          user:
            name: node_exporter
            shell: /sbin/nologin

        - name: Download and install Node Exporter
          shell: |
            cd /opt
            wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
            tar -xvf node_exporter-1.3.1.linux-amd64.tar.gz
            mv node_exporter-1.3.1.linux-amd64 node_exporter
            chown -R node_exporter:node

