version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs-app
      - python-app

  nodejs-app:
    build:
      context: ./nodejs-app
      dockerfile: Dockerfile
    expose:
      - "3000"

  python-app:
    build:
      context: ./python-app
      dockerfile: Dockerfile
    expose:
      - "5000"
