# homework-20240707/argo-cd-service-nodeport.yaml

apiVersion: v1
kind: Service
metadata:
  name: argo-cd-argocd-server
  namespace: argocd
spec:
  type: NodePort
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
      nodePort: 31800
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31500
  selector:
    app.kubernetes.io/name: argocd-server
