# kind-config.yaml

apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: yourhostel-cluster
spec:
  kubernetesVersion: "1.27.16"
  nodes:
  - role: control-plane
    image: kindest/node:v1.27.16
  - role: worker
    image: kindest/node:v1.27.16
