# homework-20240707/kind-config.yaml

apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: yourhostel-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 8080
    hostPort: 80
- role: worker
