# homework-20240707/kind-config.yaml

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31800  # HTTPS NodePort
    hostPort: 31800
    listenAddress: "0.0.0.0"  # accessible from any address
    protocol: TCP
  - containerPort: 31500  # HTTP NodePort
    hostPort: 31500
    listenAddress: "0.0.0.0"  # accessible from any address
    protocol: TCP
