# homework-20240707/kind-config.yaml

apiVersion: kind.sigs.k8s.io/v1alpha4
kind: Cluster
metadata:
  name: yourhostel-cluster
spec:
  kubernetesVersion: "v1.27.16"
  nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 8080
      hostPort: 80
  - role: worker
