# homework-20240707/kind-config.yaml

apiVersion: kind.sigs.k8s.io/v1alpha4
kind: Cluster
metadata:
  name: yourhostel-cluster
spec:
  controlPlane:
    extraPortMappings:
    - containerPort: 32000
      hostPort: 80
  nodes:
  - role: control-plane
  - role: worker
