# homework-20240707/postgresql-argo-application-variant-2.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-app-variant-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourhostel/hw_devops.git
    path: module_4/homework-20240707/postgresql-variant-2
    targetRevision: main  # or HEAD for the latest changes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true