apiVersion: v1
kind: Pod
metadata:
  name: yourhostel-secret-test
  namespace: yourhostel-database
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done;"]
  volumes:
  - name: vault-secrets
    emptyDir: {}
