# ansible/roles/c_advisor/tasks/main.yml

---
- name: Download and install cAdvisor
  shell: |
    cd /opt
    wget https://github.com/google/cadvisor/releases/download/v0.38.7/cadvisor -O cadvisor
    chmod +x cadvisor

- name: Create cAdvisor service
  copy:
    dest: /etc/systemd/system/cadvisor.service
    content: |
      [Unit]
      Description=cAdvisor
      Wants=network-online.target
      After=network-online.target

      [Service]
      ExecStart=/opt/cadvisor -port {{ cadvisor_port }}

      [Install]
      WantedBy=default.target

- name: Start and enable cAdvisor service
  systemd:
    name: cadvisor
    enabled: yes
    state: started



