# homework-20240623/ingress/yourhostel-python-ingress.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yourhostel-python-ingress
  namespace: yourhostel-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: k8s-yourhost-yourhost-b7894307af-1bd66ca2e46afb8c.elb.eu-north-1.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yourhostel-python-service
            port:
              number: 80


