# homework-20240707/postgresql/postgresql-state-full-set.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: default
spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "postgresql-role"
        vault.hashicorp.com/agent-inject-secret-admin: "secret/data/postgresql/admin"
        vault.hashicorp.com/agent-inject-template-POSTGRES_PASSWORD: |
          {{- with secret "secret/data/postgresql/admin" -}}
          POSTGRES_PASSWORD={{ .Data.data.password }}
          {{- end }}
    spec:
      serviceAccountName: demo-user
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          command:
            - sh
            - -c
            - |
              # Wait for the POSTGRES_PASSWORD file to appear
              while [ ! -f /vault/secrets/POSTGRES_PASSWORD ]; do
                echo "Waiting for POSTGRES_PASSWORD..."
                sleep 1
              done
              echo "Found POSTGRES_PASSWORD, starting PostgreSQL..."
              # Read the password from the file and export it
              export POSTGRES_PASSWORD=$(cat /vault/secrets/POSTGRES_PASSWORD)
              # Now start PostgreSQL
              exec docker-entrypoint.sh postgres
          env:
            # Control over the location of data inside the container
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            # Indicate to Kubernetes where the persistent volume should be connected
            # that after a restart you don’t lose data
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              readOnly: false
            - name: vault-secrets
              mountPath: /vault/secrets
      volumes:
        - name: vault-secrets
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 3Gi


