# homework-20240707/postgresql/postgresql-state-full-set.yaml сокк

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: default
spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "postgresql-role"
        vault.hashicorp.com/agent-inject-secret-admin: "secret/data/postgresql/admin"
        vault.hashicorp.com/agent-inject-template-POSTGRES_USER: |
          {{- with secret "secret/data/postgresql/admin" -}}
          POSTGRES_USER={{ .Data.data.username }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-POSTGRES_PASSWORD: |
          {{- with secret "secret/data/postgresql/admin" -}}
          POSTGRES_PASSWORD={{ .Data.data.password }}
          {{- end }}
    spec:
      serviceAccountName: postgresql-sa
      containers:
      - name: postgresql
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-admin-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-admin-secrets
              key: POSTGRES_PASSWORD
