# terraform/modules/argo_cd/argo-cd-values.yaml

server:
  ingress:
    enabled: true
    hosts:
      - final.tyshchenko.online
    paths:
      - /argo
    tls:
      - secretName: final-tyshchenko-online-tls
        hosts:
          - final.tyshchenko.online