---
- hosts: webservers
  become: yes
  tasks:
    - name: Ensure htop is installed
      yum:
        name: htop
        state: present

    - name: Ensure tree is installed
      yum:
        name: tree
        state: present

    - name: Display htop version
      command: htop --version
      register: htop_version

    - name: Display tree version
      command: tree --version
      register: tree_version

    - name: Print htop version
      debug:
        msg: "{{ htop_version.stdout }}"

    - name: Print tree version
      debug:
        msg: "{{ tree_version.stdout }}"

