#!/usr/bin/env bash
# v

function start_vms() {
  if [[ "$1" == "c" || "$2" == "c" ]]; then
    echo "Removing Vagrant index file..."
    rm -f ~/.vagrant.d/data/machine-index/index
  fi

  if [ "$1" == "p" ]; then
    echo "Starting all VMs with provisioning..."
    vagrant up --provision
  else
    echo "Starting all VMs without provisioning..."
    vagrant up
  fi

  echo "Executing script on master..."
  vagrant ssh jenkins_master -c "bash /vagrant/vagrant_scripts/add_worker_key_to_container.sh jenkins"
  echo "Setup completed."
}

function stop_vms() {
    echo "Stopping all VMs..."
    vagrant halt
}

function destroy_vms() {
    echo "Destroying all VMs..."
    vagrant destroy -f
}

function reload_vms() {
    echo "Reloading all VMs..."
    vagrant reload

    echo "Executing script on master after reload..."
    vagrant ssh jenkins_master -c "bash /vagrant/vagrant_scripts/add_worker_key_to_container.sh jenkins"

    echo "Reload completed."
}

case "$1" in
    l)
        start_vms "$2" "$3"
        ;;
    s)
        stop_vms
        ;;
    d)
        destroy_vms
        ;;
    r)
        reload_vms
        ;;
    *)
        echo "Usage: $0 {l|s|d|r} [p] [c]"
        echo "l: launch, s: stop, d: destroy, r: reload, p: provision, c: clear index"
        exit 1
        ;;
esac
