Vagrant.configure("2") do |config|
  # jenkins_master
  config.vm.define "jenkins_master" do |jenkins_master|
    jenkins_master.vm.box = "bento/ubuntu-20.04"
    jenkins_master.vm.network "private_network", ip: "192.168.90.10"
    jenkins_master.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
    jenkins_master.vm.provision "shell", path: "vagrant_scripts/install_docker.sh"
    jenkins_master.vm.provision "shell", path: "vagrant_scripts/docker_compose_up.sh"
    jenkins_master.vm.provision "shell", path: "vagrant_scripts/creating_user.sh", args: ["master"]
  end

  # jenkins_worker
  config.vm.define "jenkins_worker" do |jenkins_worker|
    jenkins_worker.vm.box = "bento/ubuntu-20.04"
    jenkins_worker.vm.network "private_network", ip: "192.168.90.11"
    jenkins_worker.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
    jenkins_worker.vm.provision "shell", path: "vagrant_scripts/install_docker.sh"
    jenkins_worker.vm.provision "shell", path: "vagrant_scripts/install_java.sh"
    jenkins_worker.vm.provision "shell", path: "vagrant_scripts/install_node.sh"
    jenkins_worker.vm.provision "shell", path: "vagrant_scripts/creating_user.sh", args: ["worker"]
  end
end


