# ansible/roles/grafana/tasks/main.yml
---
- name: Ensure Python dependencies are installed
  amazon_linux_extras:
    name: "python3.8"
    state: present

- name: Install pip for Python 3.8
  command: "python3.8 -m ensurepip"

- name: Upgrade pip
  command: "python3.8 -m pip install --upgrade pip"

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present
    executable: "python3.8 -m pip"

- name: Run Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    ports:
      - "{{ grafana_port }}:{{ grafana_port }}"
    env:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"

