# ansible/roles/grafana/tasks/main.yml
---
- name: Ensure Python dependencies are installed
  yum:
    name: python3-pip
    state: present

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present

- name: Run Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    ports:
      - "{{ grafana_port }}:{{ grafana_port }}"
    env:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"

