---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-secret
  namespace: python-app
spec:
  encryptedData:
    .dockerconfigjson: AgDJ0ygZtwTqtUdMLg3s3kZPAnEPMe4so5cK0Uew2pOmtCASKthph9yAmC0zTX7eCaK3ho6W2965099vBA7cmzY5o12KuaddAjDhAaqTjOb2hYhs+Hgtxyi9NmkDWRwM7Q8/NHObnYawhtRHyMj2Niszd2SWRoTViPrAEmKh569VfGRl1lpmRyQCytg12waRiUUgAAiWXHjI5Z/mHEIbuETrrXuEfWum2y34A8cCShzRcrt4GS7FVX48uWIvLmBpwaaMGw72QsSX3KKP8RxHnzUemS+lCmUby00DPOtuvRDwX1Hfo7JIpSYtD2v2lI8e0+luB9Hbc3JaQvc1QDy0yr7W5SM5BDvBCSmHbawdfbSx18i60QeS0QzIEftYamVwnAPnF3dUKEtE5HClHyXr7nWvE0fma8TcmvfuM6Z29t9t9c6TepIoesaxUPOuLjJEsGAChq1gdJy37255A8kJFHZ0QzkGZ0g17yrxjqfhCXGRQXywgIGAj7BMI9AlTxx46kp3enZ1bjWd1oZwOuiLAURGM2YX7/0it1FRAwZpQ9PVTNQGU0hT3KtCVLXyJOiRr5yq0Y5EYzFlmR1t0Yoi7envPqM/IrsvIksq1+YIuwdNGSHl8SqICRXpK9IKWup34iX7WW1VXXN4wnUBX5DaDQpldStTecdIrwE0GQOMeoH+GbvP0UeOLaYPF/B/KzqCHWTr9uSAlJ5bIT8pGLI1JTDPeYIE7TgNdJqln3YJpWDAf0IPPm/opFelKTMqrz3ihUIodYQ6/lkRzZ/hZ9e/vVFJo/mpINHFJcZbwJwCIDjWiJGCd132/vGsxKUKkJiqm9l6Nv6+VloEvOTTBOTlJpgu2Dt0JCZB7wQkate8VjRanD2kN/rfPek7TP1aokJ+PgJO0WrA5MuQJnqWT35gE1XeUiEvWfMq5JOU1A==
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-secret
      namespace: python-app
    type: kubernetes.io/dockerconfigjson
