---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-secret
  namespace: python-app
spec:
  encryptedData:
    .dockerconfigjson: AgCt0JBbj1pyC+0moiUBxEqdTXD08/60nXDAdlG1SUWwAJmv7Y9HPlLfZvquEEh5l620gNKSXxYbBA6Vod/BRwOGE2H7/UyyGBCNqHKKMkWYVnFiJRDud+Mo3QacxksDHqtgCWU04inQ1scFITcdsrewMMMwDfIdzfOLUKtRci/u6CQJDCsRW60Mp3RaukFVQSN+8bY5iIbEte5okQWES+zG6ZnvPybLcBAGJ3qj4OjcjDFkVpFU/cBjYneF8oHckz8pATOP96SNFdIaOqm4DbOJVfrRGu/H1hN50HfNConSb715mMMmi6Zg+J955LIuC7iYh6ErElWMfvZHy/TlaaiWHA8egdZbFkC5ZeYBdYhIJS18zJoqP7QtAOgHIkS+GDasIRgAv3pxq35z4Jjr/NnuDg7QfI+gb8GuAlDMATYDLOLMk+gfxSPUPsq/O89BEwvwTaqkw1EB0ayL+X0MwdeFCBHkKDJDT3AnkL03G1gvq52zjf0W2JTqXmPNI01gQf9mb1cery/k7eGhQM7NutwG2jRHhYWKienflA0s70iszuX8CGjU82kkengXtc6jqep2OLARYJwoIyxEEIDCS9vFyJySZUUBoMKWOzPMi45gRWQV5q3WRuxW717ZoFTh6I5RXUAikl0JgHbHQQlpzOE9CSW5iec2ObEAwJhdrxRKFxalLDXcYMP6ieAy1zWINKf16P5nZyT3+0PzjpwDS2+pLn8iFXrSjqpFFTMiPbkBsAOf9wsBXDBFjnGJ1Jh69MgtgO6mR1avZML4suI9LT66u0va9yE+tUb98vSBEVgn8PHmP4FCG7D4kZK4/opO7V5ZuSCLISFsWR4tNoE6H7B8eY2NwE4btxo0kINKk4qVuWsftvkNwPI1VBCFzT3I6bf15u1GK7+bYVNdvurhaZO9IDKacyoAGJDN/SrevALS4/cjuN/sfFavuHMpYps+aZWoOfU/CIgPFn7kqoFTBQ61Z5lo0YandG3fpf9lkKnUc0Y=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-secret
      namespace: python-app
    type: kubernetes.io/dockerconfigjson
