version: '3.8'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile.master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins

  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      - JENKINS_SECRET
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

networks:
  jenkins:

volumes:
  jenkins-data:
