version: '3.8'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile.master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - C:/Users/dated2/.ssh/id_rsa:/var/jenkins_home/.ssh/id_rsa:ro
      - C:/Users/dated2/.ssh/known_hosts:/var/jenkins_home/.ssh/known_hosts:ro
    networks:
      - jenkins

  jenkins-agent:
    depends_on:
      - jenkins-master
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      - JENKINS_SECRET
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - C:/Users/dated2/.ssh/id_rsa:/var/jenkins_home/.ssh/id_rsa:ro
      - C:/Users/dated2/.ssh/known_hosts:/var/jenkins_home/.ssh/known_hosts:ro
    networks:
      - jenkins

networks:
  jenkins:

volumes:
  jenkins-data:
