FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

# Tools
RUN apt-get update && \
    apt-get install -y openjdk-21-jdk git curl && \
    rm -rf /var/lib/apt/lists/*

# Jenkins
RUN curl -L https://get.jenkins.io/war-stable/latest/jenkins.war -o /opt/jenkins.war

RUN chmod 644 /opt/jenkins.war

ENV JENKINS_HOME /var/jenkins_home
VOLUME /var/jenkins_home

# Скидаємо DEBIAN_FRONTEND
ENV DEBIAN_FRONTEND=""

EXPOSE 8080 50000

# Run Jenkins
CMD ["java", "-jar", "/opt/jenkins.war"]
