FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

# Tools
RUN apt-get update && \
    apt-get install -y openjdk-21-jdk git curl && \
    rm -rf /var/lib/apt/lists/*

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
RUN groupadd -g ${gid} ${group} \
    && useradd -d "/home/${user}" -u ${uid} -g ${gid} -m -s /bin/bash ${user}

USER jenkins
WORKDIR /home/jenkins