# ansible/roles/node_exporter/tasks/main.yml
---
- name: Ensure Python dependencies are installed
  yum:
    name: python3-pip
    state: present

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present

- name: Run Node Exporter container
  docker_container:
    name: node_exporter
    image: prom/node-exporter:latest
    ports:
      - "{{ node_exporter_port }}:{{ node_exporter_port }}"
