# ansible/roles/common/tasks/main.yml

---
- name: Ensure Python dependencies are installed
  yum:
    name: python3
    state: present

- name: Upgrade pip
  command: "pip3 install --upgrade pip"

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present
    executable: "pip3"

- name: Install compatible urllib3
  pip:
    name: "urllib3==1.26.14"
    state: present
    executable: "pip3"

