---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-secret
  namespace: python-app
spec:
  encryptedData:
    .dockerconfigjson: AgCf/CyKRA8fnCht7c4FZ/SVNIQpSh2CgR2TxfvTg/1NigyNA1+MRlP+W0oUgHOoOZYQoTXlLRR8B35gD7OqE0U68lRpAmJGtnBqtPHYOjk0KnokL3RJuObOZW8oNaGMDUy8aA+awjRWxOngo7qOLXHkGXVAvTHlONBeJhvOnQODyt+98/9Jvwk0NzCur83salZ3m1b7HIhoCu4RC0fHRJ+Qi3si/kbv2gsllC4R8jdVBVZgv815I/Wfjzz5uwzEHHQiOYUU8iyUhF01p5CgIZgH+5qAGD6Ez0l7/Gm8s2t9Bo/v5iY6sEOCo6ZTM2N29mfJm7ibeCUknN1BuVqv3A18OqRntM2GNDVvqJvJySoLQMfIidZIrD08jKVO92O1vhfZPsG8kFFHtK4sDMgoYAYXXyS0F3TNSt+GqsfTjWlqdRqPzgHjrEj8ZRYqwXR7yrVJAPoBdVhEaCoQU4c5Ix3l7tgaZLSdKdB8QWdeFywjhsCpOhNmp9q7RIafoqgDv2zcCqLFFQBHGQ/cOAvFpcJudBVolp8VVdV4qeWcjicQvvl/zYx0hZ23uir8DSPNTnTyAatgw2aLXNqpkEPUSqpnWKblr6WW26lwP0VEwsxBocVEldnY9p/9foNv4G8/pVbTURqacanYRM8LaFONofjd1YjfJzhlZda70+/s15eP+I9D7ydhE45nhrhf4SPl0d/d0MmRGB/0W+F8hRN1f+DWcVLOfi3clKDfSfai7oQBr9k/eDkgtUe8ovt4dCUohxgYC2S9rqf6KPGzINK54Q8+yBTBmakKt7fZ/WYUkirF1N+ospDoci2ggdss2HukiqpEt1eE/gTJVxrUJ3OCvh5jOML4I0GmA2ZXCREgFycjxpDPQno8wUoCMGvnBTH8zMo5pWomcSDPkKGRCIUpPL8g52Ip9yBOYjH4Sox2l1fRb+inl7EaKuoa/hGd04Aa11PyAp8KtTdSOo+8WQl7DOqotHV+g5cuujTUGR48xpKbXQw=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-secret
      namespace: python-app
    type: kubernetes.io/dockerconfigjson
