---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-secret
  namespace: python-app
spec:
  encryptedData:
    .dockerconfigjson: AgAA5zHpr9gWOO9c+dNRmaXbWbasokd3aGQDn0xO3WiXRAvEBO35sPndbowiowJIm7kQH8Tx+mex5KtWyfzAuYGkR44eQ2SapjDu8+4JDn/imj62AlBqzzMRRb6mNsY8yh8DRCmbpiueQwcN16yoBirZPPUL4a0DvQGhxQuJrTkMEe9BLuhXrppWazLQ7+5VbhUbHRYs0/ZvJsiQafIz/aUQb2kBgWweCYWkm1Gnbkq+ZOgVUQoSHsBUHe/D2pNdrsEqOwnuQ1jxNudxlT2DM4DvD7Vh5Ky7C5ZBNV9TEam59qQitlZIdXNdqpKyLgIlbfWCkao31Zxuz/WnHdM84b/LYoQwssrdYIqmdNnbwdjGz3AufwaZVC52SnTrtUQtO3VVeYbYaZvRfn7ATclCYoMJTwosT7NojcF+s5fAdGNU3r8WrdA+/FZN3x30lNU+0h+O8srJvQOqnL7k2BTqQMANXq/G7jTYyembwQkJrGnvSdMVM+BK9AXbGniCeOZ89/JfJyGERPhCubYmWYWOlVoL08/i0BN/BFev13vOk5Fps7y/Yocx1fUEuRd615Jfadu3ZKLemVnGCHDtybE6UL3tzpCdRPFL1uqmrQIJP11Sk4knPD0I8oBCt329q2xSbXII+OKIb52yQKP7heHUqhGTBGOknS4ityEzzFnrwRuYFiz1fXYBJEysVb+q4EvwkxKKMnbUOn3FCjz/Vub35Vz/BI3vG3qtLpESO/9Wi6s02lRqR9mbFoNs9rRmT+9h1GJgm9mEgGD/Y8/h9wKSY1oumanaJfcPrOm0PQzIixAwJi00QKt+fQVg/oKI81dUb411Nro5uY+2Y+KUmsex0Wqccbuk4ZDWgCgmCpvnyGX1N6MKcY3oe0xDsvXIB3wOZ6q93c+b8A+dw3dMBQG0KGZe9lK9iQVQZC3c1NRZR9GOw/jWH0gfS1JFa7DAUxTXcJhdXdGuOMt+kwxlsLtG+TX5l13zfIAEA5taYmYPr/XjUgo=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-secret
      namespace: python-app
    type: kubernetes.io/dockerconfigjson
