# homework-20240707/vault/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - yourhostel-postgres-sa.yaml
  - yourhostel-vault-agent-config.yaml
  - yourhostel-vault-agent-deployment.yaml
  - yourhostel-vault-auth-rbac.yaml
