# homework-20240707/vault/yourhostel-vault-agent-config.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: yourhostel-vault-agent-config
  namespace: yourhostel-database
data:
  config.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "yourhostel-role"
        }
      }
    }

    sink "file" {
      config = {
        path = "/vault/secrets/yourhostel-secret"
      }
    }

    template {
      source = "/vault/config/secret.tmpl"
      destination = "/vault/secrets/yourhostel-env"
    }

  secret.tmpl: |
    POSTGRES_DB={{ with secret "secret/data/yourhostel-secret" }}{{ .Data.data.POSTGRES_DB }}{{ end }}
    POSTGRES_USER={{ with secret "secret/data/yourhostel-secret" }}{{ .Data.data.POSTGRES_USER }}{{ end }}
    POSTGRES_PASSWORD={{ with secret "secret/data/yourhostel-secret" }}{{ .Data.data.POSTGRES_PASSWORD }}{{ end }}



