# ansible/roles/c_advisor/tasks/main.yml
---
- name: Ensure Python dependencies are installed
  amazon_linux_extras:
    name: "python3.8"
    state: present

- name: Install pip for Python 3.8
  command: "python3.8 -m ensurepip"

- name: Upgrade pip
  command: "python3.8 -m pip install --upgrade pip"

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present
    executable: "python3.8 -m pip"

- name: Run cAdvisor container
  docker_container:
    name: cadvisor
    image: google/cadvisor:latest
    ports:
      - "{{ cadvisor_port }}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
