# ansible/roles/c_advisor/tasks/main.yml
---
- name: Ensure Python dependencies are installed
  yum:
    name: python3-pip
    state: present

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present

- name: Run cAdvisor container
  docker_container:
    name: cadvisor
    image: google/cadvisor:latest
    ports:
      - "{{ cadvisor_port }}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
