# ansible/roles/grafana/tasks/main.yml

---
- name: Install Grafana
  shell: |
    cd /tmp
    wget https://dl.grafana.com/oss/release/grafana_7.5.7_amd64.deb
    sudo yum install -y yum-utils
    sudo yum-config-manager --add-repo https://rpm.grafana.com
    sudo yum install grafana -y
  when: inventory_hostname == prometheus_host

- name: Start Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started
  when: inventory_hostname == prometheus_host