# ansible/roles/grafana/tasks/main.yml

---
- name: Install Grafana
  shell: |
    cd /tmp
    wget https://dl.grafana.com/oss/release/grafana_7.5.7_amd64.deb
    dpkg -i grafana_7.5.7_amd64.deb
  when: inventory_hostname == "prometheus_server"

- name: Start Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started
  when: inventory_hostname == "prometheus_server"
