---
- name: Run Prometheus
  docker_container:
    name: prometheus
    image: prom/prometheus
    ports:
      - "{{ prometheus_port }}:{{ prometheus_port }}"
    volumes:
      - /etc/prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"

- name: Copy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

