---
- name: Install Docker
  yum:
    name: docker
    state: present

- name: Start Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Run Prometheus
  docker_container:
    name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"

- name: Copy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
