# ansible/roles/prometheus/tasks/main.yml
---
- name: Create Prometheus configuration directory
  file:
    path: /etc/prometheus
    state: directory

- name: Copy Prometheus configuration file
  template:
    src: prometheus.json.j2
    dest: /etc/prometheus/prometheus.json

- name: Run Prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    ports:
      - "{{ prometheus_port }}:{{ prometheus_port }}"
    volumes:
      - /etc/prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.json"




