# ansible/roles/prometheus/tasks/main.yml

---
- name: Ensure Python dependencies are installed
  amazon_linux_extras:
    name: "python3.8"
    state: present

- name: Install pip for Python 3.8
  command: "python3.8 -m ensurepip"

- name: Upgrade pip
  command: "python3.8 -m pip install --upgrade pip"

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present
    executable: "python3.8 -m pip"

- name: Run Prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    ports:
      - "{{ prometheus_port }}:{{ prometheus_port }}"
    volumes:
      - /etc/prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"

- name: Copy Prometheus configuration file
  template:
    src: prometheus.json.j2
    dest: /etc/prometheus/prometheus.yml






