# hw_devops/.github/workflows/main.yml

name: Build and Push Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'module_4/homework-step-final/python/**' # comment out for debugging

# only for debugging
#      - '**'
#  list_files:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: List all files from the repo root
#      run: ls -la
#
#    - name: List files in the Dockerfile directory
#      run: ls -la module_4/homework-step-final/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short SHA
        id: vars
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Output SHA value in build
        run: |
          echo "SHA value: ${{ env.SHORT_SHA }}"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./module_4/homework-step-final/python
          file: ./module_4/homework-step-final/python/Dockerfile
          push: true
          tags: |
            yourhostel/devops-final:latest
            yourhostel/devops-final:${{ env.SHORT_SHA }}

  test_application:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull and run Docker image
        run: |
          docker pull yourhostel/devops-final:latest
          docker run -d -p 8080:8080 --name myapp yourhostel/devops-final:latest

      - name: Check application response
        run: |
          sleep 10  # Give time for the server to start
          response=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080/python-app)
          if [ "$response" -eq 200 ]; then
            echo "Application responded with 200 OK"
          else
            echo "Application failed to respond with 200 OK"
            docker logs myapp  # Check container logs
            exit 1
          fi

  update_values:
    needs: test_application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get short SHA again
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)       
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Output SHA value in update_values
        run: |
          echo "SHA value: ${{ env.SHORT_SHA }}"

      - name: Update values.yaml
        run: |
          echo "Before update:"
          cat module_4/homework-step-final/helm_charts/python-app/values.yaml
          echo "Updating tag..."
          sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/" module_4/homework-step-final/helm_charts/python-app/values.yaml
          echo "After update:"
          cat module_4/homework-step-final/helm_charts/python-app/values.yaml

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add module_4/homework-step-final/helm_charts/python-app/values.yaml
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Update Docker image tag to ${{ env.SHORT_SHA }}"
            git push origin main
          fi