# hw_devops/.github/workflows/main.yml

name: Build and Push Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'module_4/homework-step-final/python/**' # comment out for debugging

# only for debugging
#      - '**'
#  list_files:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: List all files from the repo root
#      run: ls -la
#
#    - name: List files in the Dockerfile directory
#      run: ls -la module_4/homework-step-final/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./module_4/homework-step-final/python
          file: ./module_4/homework-step-final/python/Dockerfile
          push: true
          tags: |
            yourhostel/devops-final:latest
            yourhostel/devops-final:${{ steps.vars.outputs.short_sha }}

  test_application:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull and run Docker image
        run: |
          docker pull yourhostel/devops-final:latest
          docker run -d -p 8080:8080 --name myapp yourhostel/devops-final:latest
      - name: Check application response
        run: |
          sleep 10  # Give time for the server to start
          response=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080/python-app)
          if [ "$response" -eq 200 ]; then
            echo "Application responded with 200 OK"
          else
            echo "Application failed to respond with 200 OK"
            docker logs myapp  # Check container logs
            exit 1
          fi

  update_values:
    needs: test_application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Update values.yaml
        run: |
          sed -i "s/tag: .*/tag: ${{ steps.vars.outputs.short_sha }}/" module_4/homework-step-final/helm_charts/python-app/values.yaml
      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add module_4/homework-step-final/helm_charts/python-app/values.yaml
          git commit -m "Update Docker image tag to ${{ steps.vars.outputs.short_sha }}"
          git push origin main