# hw_devops/.github/workflows/main.yml

name: Build and Push Docker image

on:
  push:
    branches:
      - main
    paths:
      - '**' # only for debugging
#      - 'module_4/homework-step-final/**'

jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: List all files from the repo root
      run: ls -la

    - name: List files in the Dockerfile directory
      run: ls -la module_4/homework-step-final/

  build:
    needs: list_files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: module_4/homework-step-final
        file: Dockerfile
        push: true
        tags: yourhostel/devops-final:latest




