# .github/workflows/main.yml

name: Build and Push Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'module_4/homework-step-final/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: module_4/homework-step-final

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./module_4/homework-step-final
        file: ./module_4/homework-step-final/Dockerfile
        push: true
        tags: yourhostel/devops-final:latest
