apiVersion: v1
kind: Service
metadata:
  name: static-site-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: static-site
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
